version: "2"

services:
  grafana:
    container_name: grafana2
    image: grafana/grafana
    ports:
      - 3001:3000
    user: "501"
    restart: always
    volumes:
      - ~/Documents/docker_projects/grafana/data:/var/lib/grafana