version: "2"

services:
  grafana:
    container_name: grafana
    image: grafana/grafana
    ports:
      - 3000:3000
    user: $ID
    restart: always
    volumes:
      - $PWD/data:/var/lib/grafana