version: "2"

services:
  grafana:
    container_name: grafana2
    image: grafana/grafana
    ports:
      - 3001:3000
    user: $ID
    restart: always
    volumes:
      - $PWD/data:/var/lib/grafana